services:
  - type: web
    name: meetopia-signaling
    env: node
    buildCommand: npm install && npm run build
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGINS
        value: https://meetopia-app.vercel.app,https://meetopia-signaling.onrender.com
    autoDeploy: true 