services:
  - type: web
    name: meetopia-signaling
    env: node
    buildCommand: npm install && npm run build && mkdir -p dist/server/public && cp -r server/public/* dist/server/public/
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGINS
        value: https://meetopia-app.vercel.app,https://meetopia-signaling.onrender.com
    healthCheckPath: /debug-env
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1 