ALTER TABLE "User"
ALTER COLUMN "lastSeenAt" TYPE TIMESTAMP(3)
USING "lastSeenAt" AT TIME ZONE 'UTC';

ALTER TABLE "Message"
ALTER COLUMN "readAt" TYPE TIMESTAMP(3)
USING "readAt" AT TIME ZONE 'UTC';

ALTER TABLE "Notification"
ALTER COLUMN "readAt" TYPE TIMESTAMP(3)
USING "readAt" AT TIME ZONE 'UTC',
ALTER COLUMN "createdAt" TYPE TIMESTAMP(3)
USING "createdAt" AT TIME ZONE 'UTC';
